/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'traveler' : null } |
  { 'business' : null };
export interface ItineraryItem {
  'day' : bigint,
  'routeDescription' : string,
  'ownedBy' : Principal,
  'foodRecommendations' : Array<string>,
  'activities' : Array<string>,
  'staySuggestions' : Array<string>,
}
export interface PackingChecklist {
  'ownedBy' : Principal,
  'items' : Array<string>,
}
export interface PromotedListing {
  'id' : string,
  'destination' : string,
  'contactInfo' : string,
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'promoText' : [] | [string],
  'category' : string,
}
export type Time = bigint;
export interface TripDetails {
  'destination' : string,
  'tripType' : string,
  'endDate' : Time,
  'interests' : [] | [string],
  'notes' : [] | [string],
  'startDate' : Time,
}
export interface TripPlan {
  'tripDetails' : TripDetails,
  'packingChecklist' : PackingChecklist,
  'sponsoredSuggestions' : Array<PromotedListing>,
  'pType' : Principal,
  'itinerary' : Array<ItineraryItem>,
}
export interface UserProfile { 'appRole' : AppUserRole, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[string, string], undefined>,
  'createPromotedListing' : ActorMethod<[PromotedListing], undefined>,
  'createTrip' : ActorMethod<[TripDetails], TripPlan>,
  'deletePromotedListing' : ActorMethod<[string], undefined>,
  'filterPromotedListingsByCategory' : ActorMethod<
    [string],
    Array<PromotedListing>
  >,
  'getAllListingsSortedByName' : ActorMethod<[], Array<PromotedListing>>,
  'getAllPromotedListings' : ActorMethod<[], Array<PromotedListing>>,
  'getAllTripPlans' : ActorMethod<[], Array<TripPlan>>,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerPromotedListings' : ActorMethod<[], Array<PromotedListing>>,
  'getCallerTripPlans' : ActorMethod<[], Array<TripPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePromotedListing' : ActorMethod<[string, PromotedListing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];