/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PromotedListing = IDL.Record({
  'id' : IDL.Text,
  'destination' : IDL.Text,
  'contactInfo' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'promoText' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const TripDetails = IDL.Record({
  'destination' : IDL.Text,
  'tripType' : IDL.Text,
  'endDate' : Time,
  'interests' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'startDate' : Time,
});
export const PackingChecklist = IDL.Record({
  'ownedBy' : IDL.Principal,
  'items' : IDL.Vec(IDL.Text),
});
export const ItineraryItem = IDL.Record({
  'day' : IDL.Nat,
  'routeDescription' : IDL.Text,
  'ownedBy' : IDL.Principal,
  'foodRecommendations' : IDL.Vec(IDL.Text),
  'activities' : IDL.Vec(IDL.Text),
  'staySuggestions' : IDL.Vec(IDL.Text),
});
export const TripPlan = IDL.Record({
  'tripDetails' : TripDetails,
  'packingChecklist' : PackingChecklist,
  'sponsoredSuggestions' : IDL.Vec(PromotedListing),
  'pType' : IDL.Principal,
  'itinerary' : IDL.Vec(ItineraryItem),
});
export const AppUserRole = IDL.Variant({
  'traveler' : IDL.Null,
  'business' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'appRole' : AppUserRole,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPromotedListing' : IDL.Func([PromotedListing], [], []),
  'createTrip' : IDL.Func([TripDetails], [TripPlan], []),
  'deletePromotedListing' : IDL.Func([IDL.Text], [], []),
  'filterPromotedListingsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PromotedListing)],
      ['query'],
    ),
  'getAllListingsSortedByName' : IDL.Func(
      [],
      [IDL.Vec(PromotedListing)],
      ['query'],
    ),
  'getAllPromotedListings' : IDL.Func(
      [],
      [IDL.Vec(PromotedListing)],
      ['query'],
    ),
  'getAllTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerPromotedListings' : IDL.Func(
      [],
      [IDL.Vec(PromotedListing)],
      ['query'],
    ),
  'getCallerTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePromotedListing' : IDL.Func([IDL.Text, PromotedListing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PromotedListing = IDL.Record({
    'id' : IDL.Text,
    'destination' : IDL.Text,
    'contactInfo' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'promoText' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const TripDetails = IDL.Record({
    'destination' : IDL.Text,
    'tripType' : IDL.Text,
    'endDate' : Time,
    'interests' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'startDate' : Time,
  });
  const PackingChecklist = IDL.Record({
    'ownedBy' : IDL.Principal,
    'items' : IDL.Vec(IDL.Text),
  });
  const ItineraryItem = IDL.Record({
    'day' : IDL.Nat,
    'routeDescription' : IDL.Text,
    'ownedBy' : IDL.Principal,
    'foodRecommendations' : IDL.Vec(IDL.Text),
    'activities' : IDL.Vec(IDL.Text),
    'staySuggestions' : IDL.Vec(IDL.Text),
  });
  const TripPlan = IDL.Record({
    'tripDetails' : TripDetails,
    'packingChecklist' : PackingChecklist,
    'sponsoredSuggestions' : IDL.Vec(PromotedListing),
    'pType' : IDL.Principal,
    'itinerary' : IDL.Vec(ItineraryItem),
  });
  const AppUserRole = IDL.Variant({
    'traveler' : IDL.Null,
    'business' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'appRole' : AppUserRole,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPromotedListing' : IDL.Func([PromotedListing], [], []),
    'createTrip' : IDL.Func([TripDetails], [TripPlan], []),
    'deletePromotedListing' : IDL.Func([IDL.Text], [], []),
    'filterPromotedListingsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PromotedListing)],
        ['query'],
      ),
    'getAllListingsSortedByName' : IDL.Func(
        [],
        [IDL.Vec(PromotedListing)],
        ['query'],
      ),
    'getAllPromotedListings' : IDL.Func(
        [],
        [IDL.Vec(PromotedListing)],
        ['query'],
      ),
    'getAllTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerPromotedListings' : IDL.Func(
        [],
        [IDL.Vec(PromotedListing)],
        ['query'],
      ),
    'getCallerTripPlans' : IDL.Func([], [IDL.Vec(TripPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePromotedListing' : IDL.Func([IDL.Text, PromotedListing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };