/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ItineraryItem {
    day: bigint;
    routeDescription: string;
    ownedBy: Principal;
    foodRecommendations: Array<string>;
    activities: Array<string>;
    staySuggestions: Array<string>;
}
export interface TripDetails {
    destination: string;
    tripType: string;
    endDate: Time;
    interests?: string;
    notes?: string;
    startDate: Time;
}
export type Time = bigint;
export interface PackingChecklist {
    ownedBy: Principal;
    items: Array<string>;
}
export interface TripPlan {
    tripDetails: TripDetails;
    packingChecklist: PackingChecklist;
    sponsoredSuggestions: Array<PromotedListing>;
    pType: Principal;
    itinerary: Array<ItineraryItem>;
}
export interface UserProfile {
    appRole: AppUserRole;
    name: string;
}
export interface PromotedListing {
    id: string;
    destination: string;
    contactInfo: string;
    owner: Principal;
    name: string;
    description: string;
    promoText?: string;
    category: string;
}
export enum AppUserRole {
    traveler = "traveler",
    business = "business"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(role: string, name: string): Promise<void>;
    createPromotedListing(listing: PromotedListing): Promise<void>;
    createTrip(trip: TripDetails): Promise<TripPlan>;
    deletePromotedListing(id: string): Promise<void>;
    filterPromotedListingsByCategory(category: string): Promise<Array<PromotedListing>>;
    getAllListingsSortedByName(): Promise<Array<PromotedListing>>;
    getAllPromotedListings(): Promise<Array<PromotedListing>>;
    getAllTripPlans(): Promise<Array<TripPlan>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerPromotedListings(): Promise<Array<PromotedListing>>;
    getCallerTripPlans(): Promise<Array<TripPlan>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePromotedListing(id: string, updatedListing: PromotedListing): Promise<void>;
}
import type { AppUserRole as _AppUserRole, ItineraryItem as _ItineraryItem, PackingChecklist as _PackingChecklist, PromotedListing as _PromotedListing, Time as _Time, TripDetails as _TripDetails, TripPlan as _TripPlan, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1);
            return result;
        }
    }
    async createPromotedListing(arg0: PromotedListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPromotedListing(to_candid_PromotedListing_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPromotedListing(to_candid_PromotedListing_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTrip(arg0: TripDetails): Promise<TripPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(to_candid_TripDetails_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TripPlan_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(to_candid_TripDetails_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TripPlan_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePromotedListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePromotedListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePromotedListing(arg0);
            return result;
        }
    }
    async filterPromotedListingsByCategory(arg0: string): Promise<Array<PromotedListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterPromotedListingsByCategory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterPromotedListingsByCategory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListingsSortedByName(): Promise<Array<PromotedListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListingsSortedByName();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListingsSortedByName();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPromotedListings(): Promise<Array<PromotedListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPromotedListings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPromotedListings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTripPlans(): Promise<Array<TripPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTripPlans();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTripPlans();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPromotedListings(): Promise<Array<PromotedListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPromotedListings();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPromotedListings();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerTripPlans(): Promise<Array<TripPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerTripPlans();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerTripPlans();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePromotedListing(arg0: string, arg1: PromotedListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePromotedListing(arg0, to_candid_PromotedListing_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePromotedListing(arg0, to_candid_PromotedListing_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AppUserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PromotedListing_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromotedListing): PromotedListing {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TripDetails_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripDetails): TripDetails {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TripPlan_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TripPlan): TripPlan {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    tripType: string;
    endDate: _Time;
    interests: [] | [string];
    notes: [] | [string];
    startDate: _Time;
}): {
    destination: string;
    tripType: string;
    endDate: Time;
    interests?: string;
    notes?: string;
    startDate: Time;
} {
    return {
        destination: value.destination,
        tripType: value.tripType,
        endDate: value.endDate,
        interests: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.interests)),
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        startDate: value.startDate
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    destination: string;
    contactInfo: string;
    owner: Principal;
    name: string;
    description: string;
    promoText: [] | [string];
    category: string;
}): {
    id: string;
    destination: string;
    contactInfo: string;
    owner: Principal;
    name: string;
    description: string;
    promoText?: string;
    category: string;
} {
    return {
        id: value.id,
        destination: value.destination,
        contactInfo: value.contactInfo,
        owner: value.owner,
        name: value.name,
        description: value.description,
        promoText: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.promoText)),
        category: value.category
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: _AppUserRole;
    name: string;
}): {
    appRole: AppUserRole;
    name: string;
} {
    return {
        appRole: from_candid_AppUserRole_n20(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tripDetails: _TripDetails;
    packingChecklist: _PackingChecklist;
    sponsoredSuggestions: Array<_PromotedListing>;
    pType: Principal;
    itinerary: Array<_ItineraryItem>;
}): {
    tripDetails: TripDetails;
    packingChecklist: PackingChecklist;
    sponsoredSuggestions: Array<PromotedListing>;
    pType: Principal;
    itinerary: Array<ItineraryItem>;
} {
    return {
        tripDetails: from_candid_TripDetails_n9(_uploadFile, _downloadFile, value.tripDetails),
        packingChecklist: value.packingChecklist,
        sponsoredSuggestions: from_candid_vec_n12(_uploadFile, _downloadFile, value.sponsoredSuggestions),
        pType: value.pType,
        itinerary: value.itinerary
    };
}
function from_candid_tuple_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    traveler: null;
} | {
    business: null;
}): AppUserRole {
    return "traveler" in value ? AppUserRole.traveler : "business" in value ? AppUserRole.business : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PromotedListing>): Array<PromotedListing> {
    return value.map((x)=>from_candid_PromotedListing_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TripPlan>): Array<TripPlan> {
    return value.map((x)=>from_candid_TripPlan_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AppUserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PromotedListing_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PromotedListing): _PromotedListing {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TripDetails_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripDetails): _TripDetails {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appRole: AppUserRole;
    name: string;
}): {
    appRole: _AppUserRole;
    name: string;
} {
    return {
        appRole: to_candid_AppUserRole_n27(_uploadFile, _downloadFile, value.appRole),
        name: value.name
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    destination: string;
    contactInfo: string;
    owner: Principal;
    name: string;
    description: string;
    promoText?: string;
    category: string;
}): {
    id: string;
    destination: string;
    contactInfo: string;
    owner: Principal;
    name: string;
    description: string;
    promoText: [] | [string];
    category: string;
} {
    return {
        id: value.id,
        destination: value.destination,
        contactInfo: value.contactInfo,
        owner: value.owner,
        name: value.name,
        description: value.description,
        promoText: value.promoText ? candid_some(value.promoText) : candid_none(),
        category: value.category
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    tripType: string;
    endDate: Time;
    interests?: string;
    notes?: string;
    startDate: Time;
}): {
    destination: string;
    tripType: string;
    endDate: _Time;
    interests: [] | [string];
    notes: [] | [string];
    startDate: _Time;
} {
    return {
        destination: value.destination,
        tripType: value.tripType,
        endDate: value.endDate,
        interests: value.interests ? candid_some(value.interests) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    traveler: null;
} | {
    business: null;
} {
    return value == AppUserRole.traveler ? {
        traveler: null
    } : value == AppUserRole.business ? {
        business: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
